Adds CRZ order type and makes date range optional for CDZ
railslove/epics pull request #133
Opened 2022-09-14 21:26 UTC by gadimbaylisahil

- It would make sense to have CRZ order type where we already have CDZ. 

Prior is for Direct Transfers where the latter is for Direct Debits. 

- Date ranges are optional for given order types, thus allowing empty values.

2022-09-14 21:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/railslove/epics?pullRequest=133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/railslove/epics?pullRequest=133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/railslove/epics?pullRequest=133) it.</sub>

2022-09-16 18:00 UTC, gadimbaylisahil commented
@bumi Would you guys be open to merge this?

2022-09-16 18:36 UTC, tobischo commented
If you'd fix that one pending comment I would consider merging it.
Still waiting for people with gem release permissions to get it released then though

2022-09-18 08:52 UTC, tobischo requested changes

2022-09-18 17:36 UTC, gadimbaylisahil commented on spec/orders/cdz_spec.rb
>    subject { described_class.new(client, "2014-09-01", "2014-09-30") }
Done. Thanks for the catch

2022-09-18 17:52 UTC, tobischo approved these changes

2022-09-21 11:30 UTC, merged